### ISSUE TITLE
Gradle build error: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by vchampion** [rapidminer/rapidminer-studio#1]
Hello

I'm trying to build rapidminer-studio and result of gradle build is 
> com.rapidminer.tools.expression.internal.function.AntlrParserProcessFunctionTest > paramWithWrongNumberOfArguments FAILED
    java.lang.NoClassDefFoundError

> com.rapidminer.tools.expression.internal.function.AntlrParserProcessFunctionTest > randWithNoArgument FAILED
    java.lang.NoClassDefFoundError

> com.rapidminer.tools.expression.internal.function.AntlrParserProcessFunctionTest > macroExistingWithDefault FAILED
    java.lang.NoClassDefFoundError

> com.rapidminer.tools.expression.internal.function.AntlrParserProcessFunctionTest > randWithWrongNumberOfArguments FAILED
    java.lang.NoClassDefFoundError

> com.rapidminer.tools.expression.internal.function.AntlrParserProcessFunctionTest > randWithWrongArgumentDouble FAILED
    java.lang.NoClassDefFoundError

> com.rapidminer.operator.performance.test.MeasuredCriterionTest > testSquaredError FAILED
    java.lang.NoClassDefFoundError at MeasuredCriterionTest.java:66

> com.rapidminer.operator.performance.test.MeasuredCriterionTest > testAbsoluteError FAILED
    java.lang.NoClassDefFoundError at MeasuredCriterionTest.java:66

> com.rapidminer.operator.performance.test.ClassificationCriterionTest > testClassificationError FAILED
    java.lang.NoClassDefFoundError at ClassificationCriterionTest.java:68

> 1137 tests completed, 1020 failed
> :test FAILED

> FAILURE: Build failed with an exception.

> * What went wrong:
> Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/champion/Projects/rapidminer-studio/build/reports/tests/index.html

Why? Is that project is not ready to contribute?

**Comment by ncwoehler** [comment]
Did you use the uploaded Gradle wrapper or another Gradle distribution to build it? Which task did you execute? If you executed the 'build' task just use 'jar' instead. This will omit the tests.

**Comment by vchampion** [comment]
I use local gradle instance 
```
------------------------------------------------------------
Gradle 2.8
------------------------------------------------------------

Build time:   2015-10-20 03:46:36 UTC
Build number: none
Revision:     b463d7980c40d44c4657dc80025275b84a29e31f

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_66 (Oracle Corporation 25.66-b17)
OS:           Linux 3.19.0-25-generic amd64
```
Yes, really, gradle jar builds application.. but how I can run it after building?

**Comment by ncwoehler** [comment]
To run the project you need to import it into Eclipse (or IntelliJ). Afterwards execute  the ```RapidMinerGUI``` class. The Gradle build script is not setup to create a running jar file I'm afraid.
