### ISSUE TITLE
Error executing background job "Updating Statistics": java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by oli-ver** [rapidminer/rapidminer-studio#15]
This exception was thrown after fetching data from a website, reading its xml content and enriching the data by a webservice (i. e. 4600 rows of data):

Exception: java.util.ConcurrentModificationException
Message: null
Stack trace:

  java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
  java.util.LinkedList$ListItr.next(LinkedList.java:888)
  com.rapidminer.example.set.AbstractExampleSet.getStatistics(AbstractExampleSet.java:566)
  com.rapidminer.gui.viewer.metadata.model.NominalAttributeStatisticsModel.updateStatistics(NominalAttributeStatisticsModel.java:115)
  com.rapidminer.gui.viewer.DataViewerTable$2.run(DataViewerTable.java:179)
  com.rapidminer.gui.tools.ProgressThread$3.run(ProgressThread.java:550)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)

**Comment by Preko** [comment]
Can you please attach the process that caused this? Or maybe a stripped down version of it?

Thanks, Zoltan
