### ISSUE TITLE
DatabaseHandler.java is not there

### ISSUE THREAD

**Issue by surabhi6** [rapidminer/rapidminer-studio#17]
Hi,
First of all I am glad that I can access the codes.

I have cloned rapidminer 5 source codes and it had folder *jdbc* inside tools. (com.rapidminer.tools.jdbc).
Source code (rm 7) that you have provided does not have that folder.
Actually I am looking for DataHandler.java file which was there in earlier version.

Please do reply.

**Comment by ncwoehler** [comment]
Hi, since RapidMiner 6 the JDBC package is not part of our open-source offering anymore. The RapidMiner 5 JDBC sources are still available of course.
