### ISSUE TITLE
Rapidminer public maven repository - 401 access denied

### ISSUE THREAD

**Issue by fmannhardt** [rapidminer/rapidminer-studio#18]
The maven repository with the RapidMiner components that is needed to build rapidminer-studio seems to be behind a login wall. When I try to access:
https://maven.rapidminer.com/content/groups/public/

I get the message: "Access Denied - Please login before attempting further requests.".

This is preventing me from building RapidMiner.

**Comment by ncwoehler** [comment]
Thanks for notifying us! Seems like we have messed up the permissions. Should be fixed now.
