### ISSUE TITLE
Incompatibility with old RapidMiner 5 processes

### ISSUE THREAD

**Issue by Markus-Go** [rapidminer/rapidminer-studio#2]
Hi,

I am very happy to see that there is now a Open Source 6.x Version of RapidMiner available :)

Unfortunately, I have difficulties running my RapidMiner 5 processes. Almost none of them could be executed. Dozens of operators seem to be disabled now and thus breaking all of my stuff.

Is it somehow possible to run old processes with the new version or should one better stay with rm5 ?

Best regards!

**Comment by ncwoehler** [comment]
Hi Markus,

I'm glad that you like the Open Core version of RapidMiner Studio 6.x :-)

But I'm afraid that this is the wrong medium to ask such a product mechanics related question. Please open a thread in our [forum](forum.rapidminer.com) instead. I think it would be a good idea to also include a RM 5.x process XML example when posting in the forum.

Best regards,
Nils
