### ISSUE TITLE
Dropbox Connection Error - RapidMiner Studio 7.6

### ISSUE THREAD

**Issue by poliveiraIPB** [rapidminer/rapidminer-studio#20]
Using RapidMiner Server 7.6 and RapidMiner Studio 7.6, when adding a connection to dropbox, i create the acess_token in my dropbox, and put him in the dropbox connection process at RapidMiner Studio, at RapidMiner Studio i can see my folders at Dropbox, but when running the process to save a results file to my dropbox, i get this error:

"Error: Error in call to API function "users/get_current_account": The given OAuth 2 access token is malformed."

I tried to set a new connection, and a new token, but the problem still occurs.

**Comment by JonasWilms** [comment]
This seems to be a bug, but you can use 
https://dropbox.github.io/dropbox-api-v2-explorer/#auth_token/from_oauth1 to create a working token

**Comment by poliveiraIPB** [comment]
I´ve tried what you have sayed, with the token generated from the Get Token. and the error is the same: "SEVERE: Process failed: com.rapidminer.operator.UserError: Could not connect to Dropbox. Reason: Error in call to API function "users/get_current_account": The given OAuth 2 access token is malformed."

**Comment by JonasWilms** [comment]
Strange, for me this creates a valid 64 character token. 

![image](https://user-images.githubusercontent.com/699045/29720759-31d4b138-89bb-11e7-9086-f67ae93b30e0.png)
Can you try to create a new token and press the "Test" Button in Studio? 
![image](https://user-images.githubusercontent.com/699045/29720867-835f716e-89bb-11e7-88c2-9fd42d7e8eaa.png)
Also press "Save all changes" if it's working.

If it's still not working you can also ask the [RapidMiner Community](https://community.rapidminer.com/)

**Comment by poliveiraIPB** [comment]
Yes for me that also creates a 64 character token.

The test button always returns a valid response, then i save all changes.

The problem always appear when I sent the process to run in rapidminer server, if i run the process locally the error does not appear.

**Comment by JonasWilms** [comment]
Then try to store the token directly in server [http://localhost:8080/faces/restricted/configurables.xhtml](http://localhost:8080/faces/restricted/configurables.xhtml)

**Comment by poliveiraIPB** [comment]
Ok if i put the token generated from Dropbox Api Explorer at: http://localhost:8080/faces/restricted/configurables.xhtml then submit and then Test Connection Parameters that works.

If i put the token generated from the link at rapidminer studio that points to (https://www.dropbox.com/oauth2/authorize?locale=en&response_type=code&client_id=XXXXX)  at: http://localhost:8080/faces/restricted/configurables.xhtml then submit and then Test Connection Parameters that doesn´t work and i get the error "Error: {"error_summary": "invalid_access_token/..", "error": {".tag": "invalid_access_token"}}."

So it must be a bug to solve to future versions.

**Comment by ncwoehler** [comment]
Thanks for the report. The bug should have been fixed in the latest version.
