### ISSUE TITLE
 Build fails on 'DefaultPublishingExtension' does not exist

### ISSUE THREAD

**Issue by janmotl** [rapidminer/rapidminer-studio#21]
After executing:
```
gradlew jar
```
I get:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'rapidminer-studio-core'.
> Extension of type 'DefaultPublishingExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, DefaultArtifactPublicationSet, ReportingExtension, EclipseModel, IdeaModel, PublishingExtension, PublishingExtension, JacocoPluginExtension]
```
I also tried (with my Gradle 4.1):
```
gradle jar -x generateVersionProperties
```
But that generates the same error message. Out of curiosity, I also tried older versions of Gradle. And Gradle 2 generated the jar.

**Comment by akontaxakis** [comment]
same problem here.!!

**Comment by ncwoehler** [comment]
If you change line 8 of _build.gradle_ to
```
classpath 'com.rapidminer.gradle:java-publishing:0.2.1'
```
it should be working again. The update to version 0.2.1 will be done in the next release.

**Comment by akontaxakis** [comment]
thanks a lot Nils, that worked for me, may I ask you an other question? I
am getting this error
Exception: java.security.AccessControlException
Message: access denied ("java.util.PropertyPermission" "*" "read,write")
when I run my custom operator any idea how to solve it?

2017-08-27 12:21 GMT+03:00 Nils Wöhler <notifications@github.com>:
