### ISSUE TITLE
org.eclipse.jgit.errors.RepositoryNotFoundException

### ISSUE THREAD

**Issue by sevenFire** [rapidminer/rapidminer-studio#25]
I wanted to build rapidminer-studio-master, so I download the source code from github:https://github.com/rapidminer/rapidminer-studio According to the README.md file, I import the project into IDEA, then execute the command gradlew jar, but the error is:
```
* What went wrong:
Execution failed for task ':generateGitRevFile.
> org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: 
E:\lyh\file\workspaces\rapidminerworkspace\rapidminer-studio-master
```

Then I open the file props.gradle,it shows that: `import org.ajoberstar.grgit.Grgit` is wrong, because it cannot resolve symbol org.ajoberstar.

So the file has obviously added a corresponding dependency in `props.gradle`. Why is it still failing to load?
```
buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath 'org.ajoberstar:grgit:0.3.+'
	}
}
import org.ajoberstar.grgit.Grgit
```

**Comment by JonasWilms** [comment]
> ### Build RapidMiner Studio Core from Source
> 1. Clone rapidminer-studio using git into a folder named rapidminer-studio-core

Please use git to clone the repository, also the local folder must be named rapidminer-studio-core
