### ISSUE TITLE
System.io Exception / Unhandle Java.io Error

### ISSUE THREAD

**Issue by Mentors4EDU** [rapidminer/rapidminer-studio#26]
Whenever I run RapidMiner.sh on XUbuntu, it prevents nancyviewbrowser or sockets needed to run other applications on my webserver. This seems to happen regardless if I use port 3333, 3339, etc on the other program. Is there a way to run RapidMiner Studio without it taking up my web sockets for other programs? Should I use RapidMiner Server instead? Any suggestions? 

`
Unhandled web-server exception: System.IO.IOException: Unable to write data to the transport connection: The socket has been shut down. ---> System.Net.Sockets.SocketException: The socket has been shut down`

I know this is a socket being used up issue because I can use my web sockets for nancyhosting or java io applications when RapidMiner is closed. However, I still need to utilize being able to use RapidMiner on that server? What IT configs or terminal commands I could do that may fix this issue?

Thanks and best regards, Andrew

**Comment by JonasWilms** [comment]
I highly doubt that this has anything to do with RapidMiner. Many people have the same issue with CoiniumServ without using RapidMiner, maybe try to run this Software in it's own docker container or VM.
