### ISSUE TITLE
jar lacks main manifest attribute

### ISSUE THREAD

**Issue by yurivict** [rapidminer/rapidminer-studio#28]
I build ```rapidminer-studio-9.3.0.jar``` using gradle, and it can't be run:
```
$ java -jar /usr/local/share/java/classes/rapidminer-studio-9.3.0.jar
no main manifest attribute, in /usr/local/share/java/classes/rapidminer-studio-9.3.0.jar
```

OS: FreeBSD 12
Building package from the port.

**Comment by yurivict** [comment]
I think that the ```jar``` section is missing: https://stackoverflow.com/questions/32567167/gradle-no-main-manifest-attribute

**Comment by marco-boeck** [comment]
This is the correct behavior, as it is mainly meant to be used as a library jar, and is not intended to start up the UI on its own. We have multiple launchers doing OS specific stuff (integrating with the top menu on OSX, looking for updates on Windows, etc). These launchers are not Open Source, so they are not part of this repo.

You can add a launcher yourself easily enough though with the following lines:
```
PlatformUtilities.initialize();
RapidMiner.setExecutionMode(RapidMiner.ExecutionMode.UI);
RapidMinerGUI.registerStartupListener(new ToolbarGUIStartupListener());
RapidMinerGUI.main(args);
```

**Comment by yurivict** [comment]
Doesn't "Studio" imply that it has UI?

**Comment by yurivict** [comment]
What is the use model? Lack of executables discourages package creation.
In FreeBSD Java (and GoLang) libraries aren't allowed to be packaged, only final executables are allowed to be packaged.
So I wouldn't create a packages then. This reduces chances that somebody would use rapidminer-studio because without a package it becomes a hassle.
