### ISSUE TITLE
Operator to consider association rules as example data.

### ISSUE THREAD

**Issue by hilnius** [rapidminer/rapidminer-studio#3]
Hi,
I'm wondering if you guys could help in creating an operator that would convert association rules into example data. I need that because I use the association rules in a subprocess and would like to combine the results in the parent process.

Thanks,

Robin

**Comment by kunmei** [comment]
missing keystore, what's wrong with it?

**Comment by JonasWilms** [comment]
Association Rules to Example Set already exists in the [Converters Extension
](https://marketplace.rapidminer.com/UpdateServer/faces/product_details.xhtml?productId=rmx_converters)
