### ISSUE TITLE
About  Missing keystore property

### ISSUE THREAD

**Issue by kobe24dh** [rapidminer/rapidminer-studio#6]
Hi
I need some help。When I was in the compiled code。hava a failed: Cannot create signed jar for rapidminer-studio. Missing keystore property.  what's keystore? 
thanks!
ghost

**Comment by ncwoehler** [comment]
Hi,

you need to change the version in `gradle.properties` to `7.1.1-SNAPSHOT`. Afterwards you should be able to build the Jar. Release versions need a keystore as they need to be signed by default.

Cheers,
Nils
